name: XcodeGenWithLocalPackage
targets:
  XcodeGenWithLocalPackage:
    type: application
    platform: iOS
    dependencies:
      - package: AppPackage
        product: AppFeature
      - package: swift-composable-architecture
        product: ComposableArchitecture
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.example.XcodeGenWithLocalPackage
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 0.0.1
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
    sources:
      - XcodeGenWithLocalPackage
schemes:
  XcodeGenWithLocalPackage:
    build:
      targets:
        XcodeGenWithLocalPackage: all
    test:
      targets:
        - package: AppPackage/AppFeatureTests
        - package: AppPackage/HomeFeatureTests
        - package: AppPackage/LoginFeatureTests
packages:
  AppPackage:
    path: AppPackage
  swift-composable-architecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    version: 1.9.2
